export const CURRENT_USER = "CURRENT_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const TOGGLE_DROPDOWN = "TOGGLE_DROPDOWN";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_SELECTED_ITEM = "REMOVE_SELECTED_ITEM";
export const DECREASE_ITEM_FROM_CART = "DECREASE_ITEM_FROM_CART";
